remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Hydrodynamic-evolution-Cast
description: Generate the hydrodynamic evolution history iteratively by diffusion model 
author: Jing-An
markdown: kramdown
kramdown:
  math_engine: mathjax
